services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # HTTP
      # - "443:443"  # HTTPS (for future SSL setup)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    secrets:
      - backend_secret_key
      - admin_password
    environment:
      ADMIN_USERNAME: "admin"
      # APP_MODE: "production" # Change to "development" or comment out for dev mode

networks:
  app-network:
    driver: bridge

secrets:
  backend_secret_key:
    file: .secrets/backend_secret_key.env
  admin_password:
    file: .secrets/admin_password.env
