version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Exposing frontend on port 5173 for Cloudflare Tunnel
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Exposing backend on port 8000 for frontend communication
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
