services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"    # HTTP
      # - "443:443"  # HTTPS (for future SSL setup)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
      # - ./certs:/etc/nginx/ssl  # SSL certificates (optional for HTTPS)
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Exposing backend on port 8000 for frontend communication
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
