name: Deploy via Cloudflare Access

on:
  push:
    branches:
      - '**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Build Docker image
        run: |
          docker compose build


  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install cloudflared
        run: |
          # Download and install cloudflared
          curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo apt-get install -f  # Fix dependencies, if any

      - name: Deploy via Cloudflare SSH
        env:
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: |
          ssh -o StrictHostKeyChecking=no mrpi@ssh.michalrajzer.com \
            -o ProxyCommand="cloudflared access ssh --hostname %h --service-token-id $CF_ACCESS_CLIENT_ID --service-token-secret $CF_ACCESS_CLIENT_SECRET" \
            "cd PersonalWebsite && \
            sudo docker compose down && \
            git fetch && \
            git checkout run-production-build && \
            git reset --hard origin/main && \
            sudo docker compose up --build -d"